### ISSUE TITLE
Uninstaller not working

### ISSUE THREAD

**Issue by E14** [wavebox/waveboxapp#225]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 1703 // 15063.332

I can select "uninstall", UAC may or may not ask me for the admin password, but either way nothing happens and the program will stay in programs listing

![image](https://user-images.githubusercontent.com/1640391/26935165-8b614ffa-4c6b-11e7-8fb3-b5d0e8bf1389.png)

**Comment by Thomas101** [comment]
Hi, could you check if squirrel created a log file under `%LocalAppData%\SquirrelTemp\SquirrelSetup.log` (e.g. 
`C:\Users\E14\AppData\Local\SquirrelTemp\SquirrelSetup.log`). This may contain some more information as to why it's failing. Also if you look under `C:\Users\E14\AppData\Local\wavebox\Wavebox.exe` is Wavebox still there or has it been removed?

**Comment by E14** [comment]
Ok... I can't check now, but your indication that wavebox puts executables in AppData gives me a hint:
Could CryptoPrevent block the execution of the uninstaller?

**Comment by Thomas101** [comment]
It's not something we've seen before, but then not something we've explicitly checked either. Generally we haven't seen any problems with Antivirus/malware products though

**Comment by Thomas101** [comment]
@E14 did you manage to get it to uninstall correctly?

**Comment by E14** [comment]
There are two files in `%LocalAppData%\wavebox`
* `Update.exe`
* `.dead`

There are is also `%LocalAppData%\SquirrelTemp` with
* `tempa` - contains a "lib" folder and ultimately a node_modules tree, no idea if that is from wavebox)
* [`SquirrelSetup.log`](https://github.com/wavebox/waveboxapp/files/1098388/SquirrelSetup2.txt) - also contains a lot of log entries from other apps than wavebox, but what's funny is the extract below

```
2017-06-08 14:10:41> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Thomas Beverley\Desktop\waveboxapp\assets\icons\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\Thomas Beverley\Desktop\waveboxapp\assets\icons\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Thomas Beverley\Desktop\waveboxapp\assets\icons\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
```
It knows you ;) But not surprisingly, it did not find your user profile on my system!

Further back, it seems that it failed to install properly, though the app actually did start (??), see cleaned log file in attach

**Comment by Thomas101** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Take a look at windows installer icon issue](https://trello.com/c/nH70neog/234-take-a-look-at-windows-installer-icon-issue)

**Comment by Thomas101** [comment]
Awesome thanks for the logs :)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
The icon on the installed version has been fixed. We've also updated squirrel (the install handler) which should make sure the uninstall doesn't end up in the state that you ended up with it in
