### ISSUE TITLE
Failed to build on Fedora 26

### ISSUE THREAD

**Issue by aditiapratama** [wavebox/waveboxapp#366]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.6 Beta channel
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 26 64 bit.

I'm using nvm to build wavebox. 
here 's the log 
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/aditia/.nvm/versions/node/v7.9.0/bin/node',
1 verbose cli   '/home/aditia/.nvm/versions/node/v7.9.0/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'wavebox' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly fetchPackageMetaData wavebox
5 silly fetchNamedPackageData wavebox
6 silly mapToRegistry name wavebox
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'wavebox',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'wavebox',
9 silly mapToRegistry   name: 'wavebox',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/wavebox
11 verbose request uri https://registry.npmjs.org/wavebox
12 verbose request no auth needed
13 info attempt registry request try #1 at 7:27:31 AM
14 verbose request id 4cc1eb0ba233b33f
15 http request GET https://registry.npmjs.org/wavebox
16 http 404 https://registry.npmjs.org/wavebox
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Mon, 28 Aug 2017 00:27:32 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-sin18026-SIN',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1503880052.676595,VS0,VE949',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Mon, 28 Aug 2017 00:27:32 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-sin18026-SIN',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1503880052.676595,VS0,VE949',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/wavebox
19 silly fetchPackageMetaData     at makeError (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
19 silly fetchPackageMetaData     at Request._callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
19 silly fetchPackageMetaData     at Request.self.callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1081:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1001:12)
19 silly fetchPackageMetaData  error for wavebox { Error: Registry returned 404 for GET on https://registry.npmjs.org/wavebox
19 silly fetchPackageMetaData     at makeError (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
19 silly fetchPackageMetaData     at Request._callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
19 silly fetchPackageMetaData     at Request.self.callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1081:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1001:12) pkgid: 'wavebox', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/wavebox
20 verbose stack     at makeError (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
20 verbose stack     at Request._callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
20 verbose stack     at Request.self.callback (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:194:7)
20 verbose stack     at Request.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1081:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at IncomingMessage.<anonymous> (/home/aditia/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/request/request.js:1001:12)
21 verbose statusCode 404
22 verbose pkgid wavebox
23 verbose cwd /home/aditia/git/apps/waveboxapp
24 error Linux 4.12.8-300.fc26.x86_64
25 error argv "/home/aditia/.nvm/versions/node/v7.9.0/bin/node" "/home/aditia/.nvm/versions/node/v7.9.0/bin/npm" "bugs" "wavebox"
26 error node v7.9.0
27 error npm  v4.2.0
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/wavebox
30 error 404
31 error 404 'wavebox' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

```

**Comment by Thomas101** [comment]
Hi, did you follow the [build instructions](https://github.com/wavebox/waveboxapp#building-wavebox) on the homepage? At which step did you get this error?

**Comment by aditiapratama** [comment]
@Thomas101 I've got it error in following steps 
> To run compile and run the app: `npm start`

Let me know if you need anything?

Thanks

**Comment by Thomas101** [comment]
The error looks like it's trying to find the Wavebox package on npmjs.org - but we don't publish it there. I've managed to get a similar error running `npm install wavebox` but that would be expected. I've tried it on a clean box but it seems to for me.

When you ran `npm run install:all` and `npm run rebuild:electron` if you look up in the log were there any errors? It could be that a dependency failed to install along the way, but I'm just stabbing in the dark really.

**Comment by aditiapratama** [comment]
@Thomas101 here I attach the log from `npm run install:all`

[log_install.txt](https://github.com/wavebox/waveboxapp/files/1265998/log_install.txt)

for `npm run rebuild:electron` I've got following :
```bash
> wavebox@3.3.1 rebuild:electron /home/aditia/git/apps/waveboxapp
> electron-rebuild -f -m src/app -v 1.7.5 -t prod,optional && electron-rebuild -f -m src/guest -v 1.7.5 -t prod,optional

✔ Rebuild Complete
✔ Rebuild Complete

```

**Comment by Thomas101** [comment]
Hmmm, that looks all good. What happens if you try the following two commands...

```
npm run webpack
npm run dev:run
```

... it should be the same result as running `start` but might give an indication as to which step it's failing on

**Comment by aditiapratama** [comment]
okay running `npm run webpack` output the following

```bash
> wavebox@3.3.1 webpack /home/aditia/git/apps/waveboxapp
> webpack

[DEVELOPMENT BUILD]
[FULL SOURCEMAPS]
[NOTIFICATIONS_ENABLED]
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/fonts has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/icons has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/images has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/app has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/scenes/content has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/scenes/mailboxes has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/scenes/bridge has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/scenes/monitor has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/guest has been removed.
clean-webpack-plugin: /home/aditia/git/apps/waveboxapp/bin/guestApi has been removed.
Error: EMFILE: too many open files, open '/home/aditia/git/apps/waveboxapp/bin/app/node_modules/eslint/conf/eslint-recommended.js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wavebox@3.3.1 webpack: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wavebox@3.3.1 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aditia/.npm/_logs/2017-08-31T08_08_41_683Z-debug.log
```

**Comment by Thomas101** [comment]
It's looks like the open file limit isn't high enough. Webpack is very access heavy when building the codebase. You'll need to increase ulimit - some more info on that [here](https://ro-che.info/articles/2017-03-26-increase-open-files-limit) although exactly how you do it depends on fedora.

**Comment by aditiapratama** [comment]
@Thomas101 yes thank you, raising open file limit via systemd in Fedora works, but another error show up, I can't connect to any account via run app, It says it can't connect to internet. Any workaround to solve this?

**Comment by Thomas101** [comment]
there's normally an error code on that screen, what's that come up as?

**Comment by aditiapratama** [comment]
![image](https://user-images.githubusercontent.com/982553/29972540-a0e690d2-8f56-11e7-869b-ce47a085326f.png)

I've got that image

**Comment by Thomas101** [comment]
If you try wiping `~/.local/share/wavebox/` and relaunch any luck?

**Comment by aditiapratama** [comment]
nope, still having the same issue. Here I collect the `npm run webpack` logs
[log_webpack.txt](https://github.com/wavebox/waveboxapp/files/1270474/log_webpack.txt)

**Comment by Thomas101** [comment]
Can you double check the api key is correct in `credentials.js`. It should be exactly the same including any trailing equals

**Comment by aditiapratama** [comment]
@Thomas101 i re-add exisitng key and now wavebox work like a charm. Thank you so much for assisting. I'll mark this as a solved
