### ISSUE TITLE
Unable to launch Wavebox 3.6.0 in High Sierra 10.13.2

### ISSUE THREAD

**Issue by sryanb** [wavebox/waveboxapp#512]
* Which version of Wavebox are you using? [3.6.0]

* Which Operating System are you using? [Mac OSX High Sierra 10.13.2]

Using the application launcher, the Wavebox "start screen" appears, says "Starting Wavebox" with the logo spinning, but hangs here and never loads. Developer console shows: 

```
Bootstrap failed TypeError: Cannot read property 'partition' of undefined
    at Object.keys.forEach (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:143470)
    at Array.forEach (native)
    at l.handleLoad (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:143253)
    at a.filter.every (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:31720)
    at Array.every (native)
    at l (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:31695)
    at l (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:31326)
    at Object.P.dispatchToken.e.dispatcher.register [as ID_2] (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:1:31663)
    at e._invokeCallback (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:42:189050)
    at e.dispatch (file:///Applications/Wavebox.app/Contents/Resources/app/bin/scenes/mailboxes/mailboxes.js:42:188851)```

**Comment by sryanb** [comment]
Closed issue, removed the wavebox folder from ~/Librarby/Application Support and relaunched fine.

**Comment by Thomas101** [comment]
Thanks! Let me know if this comes up again.

If you still have the `Application Support/Wavebox` folder laying around, it would be great to grab some extra info from it. Maybe we can find the underlying cause!
